import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import NavBar from "./component/navbar";

export default function Home() {
  return (
    <div>
      <Head>
        <title>PathPlay - Assessment</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar></NavBar>
    </div>
  );
}
